### PR TITLE
Add appengine/v2 memcache support

### PR DESCRIPTION
**Pull request by faisalraja**
This will allow us to use 1st gen memcache on 2nd gen deployments.

### CODE REVIEW

**Comment by jongillham** [comment]
Hi @faisalraja thanks for this. I'm out of the loop with regards to the current state of App Engine so I have asked for a review by @someone1. I see it's just a bump to using the App Engine v2 API instead of v2 - which is great.

**Comment by faisalraja** [comment]
@jongillham Yes, details [here](https://cloud.google.com/appengine/docs/standard/go/release-notes#September_27_2021). You can now basically use legacy apis on runtime go112+ by adding app_engine_apis: true in your app.yaml and deploying it with gcloud beta app deploy ./app.yaml

I have this deployed on one of my production apps.

**Comment by someone1** [comment]
LGTM! Thank you for the contribution!

**Comment by faisalraja** [comment]
@someone1 can you tag this release to v2.0.5? Thanks

**Pull request merged**
