### PR TITLE
Add lint and race checks with associated fixes

### PR DESCRIPTION
**Pull request by someone1**
This package is breaking my CI pipeline on race checks. These changes should fix that and adding the checks to CI to prevent future regressions.

### CODE REVIEW

**Comment by someone1** [comment]
Let me know if you have any comments/questions. Hoping to get this merged and tagged as a new version immediately after! For now we're just merging in failing pipelines

**Comment by jongillham** [comment]
I've had a quick look through and it all seems in order. I don't particularly like named return values but it's the only way to return a deferred statement'. value.

I've given you collaborator rights so feel free to merge when you are happy!

**Comment by someone1** [comment]
Thanks for the upgrade though I don't seem to be able to merge this in. 

I agree with the named parameters sentiment - I don't know of a more elegant solution.

**Comment by someone1** [comment]
Scratch that - had to accept the invite first.

**Pull request merged**
